# ----
# Site

title: OpenFreeEnergy
url: "https://openfree.energy/"
baseurl:
remote_theme: CloudCannon/hydra-jekyll-template
google_analytics_key: ""  # must be empty string to disable (theme issue)
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: # TODO
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Hydra Template
  links:
    - https://github.com/CloudCannon/hydra-jekyll-template  # TODO

# -----
# Build

timezone: Etc/UTC

collections:
  team:
   _hide_content: true
  projects:
  jobs:
    output: true
  ecosystem:
    output: true

ecosystem_catalog:
  categories:
    # name is the name used in YAML; label is the natural language label
    - name: "atommappers"
      label: "Atom Mappers"
    - name: "networkplanners"
      label: "Network Planners"
    - name: "protocols"
      label: "Protocols"
  category_labels:
    atommapper: "Atom Mappers"
    networkplanner: "Network Planners"
    protocol: "Protocols"

paginate: 10
paginate_path: "/news/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
      type: "team"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "jobs"
    values:
      layout: "job"
  - scope:
      path: ""
      type: "ecosystem"
    values:
      layout: "ecosystem-entry"
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - environment.yml
  - assets/css/screen.diff

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
    - RSS
    - GitHub  # this doesn't work

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window
